#!/usr/bin/env bash
# school file description

MINE="school"

if [ -e "$MINE" ]
then
    echo "school file exists"
    if [ ! -s "$MINE" ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$MINE" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
